name: Publication to GitHub Pages
on:
  push:
    branches:
      - main
  workflow_run:
    workflows: [lint]
    branches: [main]
    types: [completed]

jobs:
  build:
    name: Deploy docs
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.26
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           CUSTOM_DOMAIN: optionaldomain.com
#           CONFIG_FILE: folder/mkdocs.yml
#           EXTRA_PACKAGES: build-base
#           REQUIREMENTS: folder/requirements.txt
