name: Test build site
on:
  pull_request:
  workflow_run:
    workflows: [ Lint-markdown ]
    types: [completed]

jobs:
  test:
    name: Test build
    if: ${{ contains(github.event.workflow_run.conclusion, 'success') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.26
