name: Test build site
on:
  pull_request:

jobs:
  test:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.26
